const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
    FETCH_TRANSACTION: 'FETCH_TRANSACTION',
    SET_TRANSACTION: 'SET_TRANSACTION',
    FETCH_ACCOUNT: 'FETCH_ACCOUNT',
    SET_ACCOUNT: 'SET_ACCOUNT'
}

export default Constants;